Repository vmware/powershell-module-for-vmware-cloud-foundation, pull requests merged in 2022-02, with the labels that each got.

#134 Update project community health
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/docs.yml
  .github/ISSUE_TEMPLATE/enhancement.yml
  .github/comment_template.md
  .github/pull_request_template.md
  .github/workflows/issue-greeting.yml
  .github/workflows/lock-threads.yml
  .github/workflows/pull-request-sizing.yml
  .github/workflows/pull-request-status.yml
  .github/workflows/stale.yml
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  LICENSE
  NOTICE
  README.md
Labels: documentation

#138 API for managing SOS
  PowerVCF.psm1
  SampleJSON/SOS/supportBundle.json
  SampleJSON/SOS/systemHealthChecks.json
  docs/functions/SoS Functions/Get-VCFHealthSummaryTask.md
  docs/functions/SoS Functions/Get-VCFSupportBundleTask.md
  docs/functions/SoS Functions/Request-VCFHealthSummaryBundle.md
  docs/functions/SoS Functions/Request-VCFSupportBundle.md
  docs/functions/SoS Functions/Start-VCFHealthSummary.md
  docs/functions/SoS Functions/Start-VCFSupportBundle.md
Labels: documentation, enhancement, size/l

#136 Add Version Check for Federation Functions
  CHANGELOG.md
  PowerVCF.psm1
Labels: bug, enhancement, size/l
