Repository vmware/powershell-module-for-vmware-cloud-foundation, pull requests merged in 2023-09, with the labels that each got.

#219 feat: add credential auto-rotate policy
  CHANGELOG.md
  PowerVCF.psd1
  PowerVCF.psm1
  docs/documentation/functions/credentials/Set-VCFCredentialAutoRotatePolicy.md
  mkdocs.yml
Labels: enhancement

#220 fix: update `validatejsoninput` function
  CHANGELOG.md
  PowerVCF.psd1
  PowerVCF.psm1
Labels: bug, dco-required

#222 feat: add proxy configuration
  CHANGELOG.md
  PowerVCF.psd1
  PowerVCF.psm1
  docs/documentation/functions/proxy/Get-VcfProxy.md
  docs/documentation/functions/proxy/Set-VcfProxy.md
  docs/documentation/functions/releases/Get-VCFRelease.md
  mkdocs.yml
  samples/proxy/proxySpec.json
Labels: enhancement

#223 feat: add `-id` and `-vdses` options to `Get-VcfCluster`
  CHANGELOG.md
  PowerVCF.psd1
  PowerVCF.psm1
  docs/documentation/functions/clusters/Get-VCFCluster.md
Labels: enhancement

#224 chore: cmdlet and docs updates (part 1)
  PowerVCF.psd1
  PowerVCF.psm1
  docs/documentation/functions/aria-suite/aria-automation/Get-VCFVra.md
  docs/documentation/functions/aria-suite/aria-automation/Get-VCFvRA.md
  docs/documentation/functions/aria-suite/aria-operations-logs/Get-VCFVrli.md
  docs/documentation/functions/aria-suite/aria-operations-logs/Get-VCFVrliConnection.md
  docs/documentation/functions/aria-suite/aria-operations-logs/Get-VCFvRLI.md
  docs/documentation/functions/aria-suite/aria-operations-logs/Get-VCFvRLIConnection.md
  docs/documentation/functions/aria-suite/aria-operations-logs/Set-VCFVrliConnection.md
  docs/documentation/functions/aria-suite/aria-operations/Get-VCFVrops.md
  docs/documentation/functions/aria-suite/aria-operations/Get-VCFVropsConnection.md
  docs/documentation/functions/aria-suite/aria-operations/Get-VCFvROPSConnection.md
  docs/documentation/functions/aria-suite/aria-operations/Set-VCFVropsConnection.md
  docs/documentation/functions/aria-suite/aria-suite-lifecycle/Get-VCFVrslcm.md
  docs/documentation/functions/aria-suite/aria-suite-lifecycle/Get-VCFvRSLCM.md
  docs/documentation/functions/aria-suite/aria-suite-lifecycle/New-VCFVrslcm.md
  docs/documentation/functions/aria-suite/aria-suite-lifecycle/Remove-VCFVrslcm.md
  docs/documentation/functions/aria-suite/aria-suite-lifecycle/Remove-VCFvRSLCM.md
  docs/documentation/functions/aria-suite/aria-suite-lifecycle/Reset-VCFVrslcm.md
  docs/documentation/functions/aria-suite/aria-suite-lifecycle/Reset-VCFvRSLCM.md
  docs/documentation/functions/aria-suite/workspace-one-access/Get-VCFWsa.md
  docs/documentation/functions/authentication/Connect-CloudBuilder.md
  docs/documentation/functions/authentication/Request-VCFToken.md
  docs/documentation/functions/iam/Get-VCFRole.md
  docs/documentation/functions/iam/Get-VCFUser.md
  docs/documentation/functions/iam/New-VCFGroup.md
  docs/documentation/functions/iam/New-VCFServiceUser.md
  docs/documentation/functions/iam/New-VCFUser.md
  docs/documentation/functions/iam/Remove-VCFUser.md
  docs/documentation/functions/proxy/Get-VCFProxy.md
  docs/documentation/functions/proxy/Set-VCFProxy.md
  mkdocs.yml
Labels: chore

#225 chore: cmdlet and docs updates (part 2)
  CHANGELOG.md
  PowerVCF.psd1
  PowerVCF.psm1
  docs/documentation/functions/avns/Add-VCFApplicationVirtualNetwork.md
  docs/documentation/functions/avns/Get-VCFApplicationVirtualNetwork.md
  docs/documentation/functions/backup-restore/Get-VCFBackupConfiguration.md
  docs/documentation/functions/backup-restore/Get-VCFRestoreTask.md
  docs/documentation/functions/backup-restore/Set-VCFBackupConfiguration.md
  docs/documentation/functions/backup-restore/Start-VCFBackup.md
  docs/documentation/functions/backup-restore/Start-VCFRestore.md
  docs/documentation/functions/bundles/Get-VCFBundle.md
  docs/documentation/functions/bundles/Request-VCFBundle.md
  docs/documentation/functions/bundles/Start-VCFBundleUpload.md
  docs/documentation/functions/certificates/Get-VCFCertificate.md
  docs/documentation/functions/certificates/Get-VCFCertificateAuthority.md
  docs/documentation/functions/certificates/Get-VCFCertificateCsr.md
  docs/documentation/functions/certificates/Remove-VCFCertificateAuthority.md
  docs/documentation/functions/certificates/Request-VCFCertificate.md
  docs/documentation/functions/certificates/Request-VCFCertificateCsr.md
  docs/documentation/functions/certificates/Set-VCFCertificate.md
  docs/documentation/functions/certificates/Set-VCFMicrosoftCa.md
  docs/documentation/functions/certificates/Set-VCFOpensslCa.md
  docs/documentation/functions/fips/Get-VCFFipsMode.md
  docs/documentation/getting-started/usage.md
  mkdocs.yml
Labels: chore

#228 chore: update issue forms
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/docs.yml
  .github/ISSUE_TEMPLATE/enhancement.yml
  .github/workflows/project.yml
Labels: chore

#227 chore: update cmdlet metadata and formatting
  CHANGELOG.md
  PowerVCF.psd1
  PowerVCF.psm1
Labels: chore

#231 feat: add support to identity provider apis for add, remove, and get
  CHANGELOG.md
  PowerVCF.psd1
  PowerVCF.psm1
  docs/documentation/functions/idp/Add-VCFEmbeddedIdentitySource.md
  docs/documentation/functions/idp/Add-VCFExternalIdentitySource.md
  docs/documentation/functions/idp/Get-VCFIdentityProvider.md
  docs/documentation/functions/idp/New-VCFIdentityProvider.md
  docs/documentation/functions/idp/Remove-VCFIdentityProvider.md
  docs/documentation/functions/idp/Update-VCFEmbeddedIdentitySource.md
  docs/documentation/functions/idp/Update-VCFIdentityProvider.md
  mkdocs.yml
  samples/idp/embeddedIdpSpec.json
  samples/idp/externalIdpSpec.json
Labels: enhancement

#232 chore: update version checks and rest syntax
  PowerVCF.psd1
  PowerVCF.psm1
Labels: chore, technical-debt

#233 chore(ci): release gha
  .github/workflows/release.yml
Labels: chore, github-actions
