Repository vmware/powershell-module-for-vmware-cloud-foundation, pull requests merged in 2024-07, with the labels that each got.

#281 fix: update exceptions in `Get-VcfTask`
  CHANGELOG.md
  PowerVCF.psd1
  PowerVCF.psm1
Labels: bug, documentation

#282 fix: json param in `Set-VCFCluster`
  PowerVCF.psd1
  PowerVCF.psm1
Labels: bug, documentation, needs-review

#288 fix: Add Content-Type to default VCF request headers
  CHANGELOG.md
  PowerVCF.psd1
  PowerVCF.psm1
Labels: bug, documentation, needs-review

#289 feat: Enhance ResponseException function to accept optional JSON payload
  CHANGELOG.md
  PowerVCF.psd1
  PowerVCF.psm1
Labels: documentation, needs-review
